services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client 
    image: rmysterio445/library-app-client:latest # to name the image after build and use inside docker file of server to copy dist folder

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    image: rmysterio445/library-app:latest
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    depends_on:
      - client
