version: "3.8"
services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_c 
    image: library-app-client # to name the image after build and use inside docker file of server to copy dist folder

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_c
    image: library-app
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    depends_on:
      - client
