name: ci
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build image from docker-compose
        run: docker-compose build
        
      - name: push the image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/library-app:latest
          
